nodeLinker: node-modules
npmMinimalAgeGate: 3d
npmPreapprovedPackages:
  - '@backstage/*'

npmScopes:
  snoby-demo-org:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: '${YARN_NPM_AUTH_TOKEN}'

yarnPath: .yarn/releases/yarn-4.13.0.cjs
